# packages/wiki-io/src/wiki_io/_graph_protocol.py
"""Structural protocol for the graph-reader surface wiki-io consumes.

Mirrors the subset of `graph_io.handle.GraphReader`'s methods actually called
from `entity_lookup.py`, `index_generator.py`, and `entity_writer.py` — lets
wiki-io type its reader parameters without depending on graph-io at runtime.
Method signatures are copied verbatim from `GraphReader`; if `GraphReader`'s
shape changes, this protocol must be updated by hand — there is no structural
enforcement (see the epic's risk notes).
"""

from __future__ import annotations

from typing import Any, Protocol


class GraphReaderLike(Protocol):
    def package_for_file(self, *, path: str) -> tuple[str, str] | None: ...

    def entity_by_name(
        self, *, name: str, kinds: tuple[str, ...] = ("package", "class", "function", "method", "domain")
    ) -> list[tuple]: ...

    def package_or_app_by_dir(self, *, path: str) -> tuple | None: ...

    def files_in_node(self, node_id: int) -> list[tuple]: ...

    def qualifying_domains(self, *, kind: str, name: str, uri: str = "") -> set[str]: ...

    def consumer_packages_in_domain(
        self, *, kind: str, entity_uri: str = "", entity_name: str = "", domain_name: str
    ) -> tuple[str, ...]: ...

    def consumer_packages(self, *, kind: str, entity_uri: str = "", entity_name: str = "") -> tuple[str, ...]: ...

    def list_repositories(self) -> list[Any]: ...

    def list_domains(self) -> list[Any]: ...

    def list_packages(self) -> list[Any]: ...

    def list_apps(self) -> list[Any]: ...

    def list_test_suites(self) -> list[Any]: ...

    def list_dependencies(self) -> list[Any]: ...

    def list_agent_plugins(self) -> list[Any]: ...

    def subdomains(self, parent_name: str) -> list[str]: ...

    def is_top_level_domain(self, name: str) -> bool: ...

    def internal_dependencies_of(self, *, name: str) -> list[str]: ...

    def describe_repository(self) -> Any: ...

    def describe_package(self, *, name: str) -> Any: ...

    def describe_app(self, *, name: str) -> Any: ...

    def describe_domain(self, *, name: str) -> Any: ...

    def describe_test_suite(self, *, suite_name: str) -> Any: ...

    def describe_dependency(self, *, ecosystem: str, name: str) -> Any: ...

    def describe_agent_plugin(self, *, name: str) -> Any: ...
