"""`gw graph suggest-resources` — propose graph.resources from graph facts.

Deterministic matcher pass (graph_io.resource_matchers) → dedupe against
declared graph.resources → paste-ready YAML in the gitignored .graph-wiki dir.
Mirrors propose_domains (never writes the manifest; the user copies keepers in).
"""

from __future__ import annotations

from pathlib import Path

import typer
import yaml
from graph_io import resource_matchers
from graph_io.store import read_only_connect
from workspace_io.manifest import read_graph_resource_matchers, read_graph_resources
from workspace_io.paths import graph_dir, manifest_path

from graph_wiki_core.commands._paths import _resolve_paths

_BANNER = (
    "# Suggested architecture resources — generated by `gw graph suggest-resources`.\n"
    "# Copy the entries you want to keep into `.graph-wiki.yaml` under graph.resources.\n"
    "# Already-declared resources are excluded. This file is gitignored.\n"
)


def compute_and_write(workspace_root: Path) -> tuple[Path, int]:
    """Core logic (testable without Typer). Returns (output_path, n_suggestions)."""
    db_path = graph_dir(workspace_root) / "code.db"
    matchers = read_graph_resource_matchers(manifest_path(workspace_root))
    existing = set(read_graph_resources(manifest_path(workspace_root)).keys())

    conn = read_only_connect(db_path)
    try:
        suggestions = resource_matchers.compute_suggestions(conn, matchers)
    finally:
        conn.close()

    # Dedupe against declared resources, then group provides/consumes per resource.
    grouped: dict[str, dict] = {}
    for s in suggestions:
        if s.resource in existing:
            continue
        entry = grouped.setdefault(s.resource, {})
        if s.resource_kind:
            entry["resource_kind"] = s.resource_kind
        if s.scope:
            entry["scope"] = s.scope
        if s.role == "provides":
            entry["provided_by"] = s.source_name
        else:
            entry.setdefault("consumed_by", []).append(s.source_name)

    out_path = graph_dir(workspace_root) / "resources.proposed.yaml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if grouped:
        body = yaml.safe_dump({"graph": {"resources": grouped}}, sort_keys=True, default_flow_style=False)
    else:
        body = "# no new resources suggested\n"
    out_path.write_text(_BANNER + body, encoding="utf-8")
    return out_path, len(grouped)


def suggest_resources_cmd(
    workspace: str = typer.Option("", "--workspace", help="Workspace root (defaults to GRAPH_WIKI_WORKSPACE)"),
) -> None:
    """Propose graph.resources entries from existing graph facts."""
    _repo_root, workspace_root = _resolve_paths(workspace)
    out_path, n = compute_and_write(workspace_root)
    typer.echo(f"Wrote {n} suggested resource(s) to {out_path}")
