"""`gw graph suggest-resources` — propose graph.resources from graph facts.

Deterministic matcher pass (graph_io.resource_matchers) → dedupe against
declared graph.resources → paste-ready YAML in the gitignored .graph-wiki dir.
Mirrors propose_domains (never writes the manifest; the user copies keepers in).
"""

from __future__ import annotations

from pathlib import Path

import graph_io
import typer
import yaml
from graph_io import GraphNotInitializedError, resource_matchers
from graph_io.resource_matchers import validate_matchers
from workspace_io.manifest import read_graph_resource_matchers, read_graph_resources
from workspace_io.paths import graph_dir, manifest_path

from graph_wiki_core.commands._paths import _resolve_paths

_BANNER = (
    "# Suggested architecture resources — generated by `gw graph suggest-resources`.\n"
    "# Copy the entries you want to keep into `.graph-wiki.yaml` under graph.resources.\n"
    "# Already-declared resources are excluded. This file is gitignored.\n"
)


class InvalidMatcherRules(Exception):
    """Raised when graph.resource_matchers contains invalid rules (command → exit 2)."""

    def __init__(self, errors: list[str]) -> None:
        super().__init__("invalid resource_matcher rules")
        self.errors = errors


def compute_and_write(workspace_root: Path) -> tuple[Path, int]:
    """Core logic (testable without Typer). Returns (output_path, n_suggestions).

    Raises InvalidMatcherRules (before writing anything) if any rule is malformed.
    """
    matchers = read_graph_resource_matchers(manifest_path(workspace_root))
    errors = validate_matchers(matchers)
    if errors:
        raise InvalidMatcherRules(errors)

    existing = set(read_graph_resources(manifest_path(workspace_root)).keys())

    reader = graph_io.open_reader(workspace_root)
    try:
        suggestions = resource_matchers.compute_suggestions(reader, matchers)
    finally:
        reader.close()

    # Group by the (resource_name, kind) join key so a provider and consumer that
    # captured the same token coalesce into one entry. Dedupe of (resource, role,
    # source) already happened in compute_suggestions.
    grouped: dict[tuple[str, str | None], dict] = {}
    providers: dict[tuple[str, str | None], list[str]] = {}
    consumers: dict[tuple[str, str | None], set[str]] = {}
    for s in suggestions:
        if s.resource in existing:
            continue
        key = (s.resource, s.resource_kind)
        entry = grouped.setdefault(key, {})
        if s.resource_kind:
            entry["resource_kind"] = s.resource_kind
        if s.subtype:
            entry["subtype"] = s.subtype
        if s.scope:
            entry["scope"] = s.scope
        if s.role == "provides":
            providers.setdefault(key, []).append(s.source_name)
        else:
            consumers.setdefault(key, set()).add(s.source_name)

    # Finalize provided_by / consumed_by per group.
    multi_provider_keys: list[str] = []
    for key, entry in grouped.items():
        provs = sorted(set(providers.get(key, [])))
        if len(provs) == 1:
            entry["provided_by"] = provs[0]
        elif len(provs) > 1:
            entry["provided_by"] = provs
            multi_provider_keys.append(key[0])
        cons = sorted(consumers.get(key, set()))
        if cons:
            entry["consumed_by"] = cons

    # Collapse the (name, kind) keys back to name-keyed YAML.
    # YAML output is name-keyed. If two suggestions share a name but differ in kind
    # (separate (name, kind) groups), the last one wins here — an accepted limitation
    # of the propose-only file; the human disambiguates on paste-in.
    flat: dict[str, dict] = {name: entry for (name, _kind), entry in grouped.items()}

    out_path = graph_dir(workspace_root) / "resources.proposed.yaml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if flat:
        body = yaml.safe_dump({"graph": {"resources": flat}}, sort_keys=True, default_flow_style=False)
        for rname in sorted(set(multi_provider_keys)):
            body = body.replace(f"    {rname}:\n", f"    {rname}:  # WARN multiple providers\n", 1)
    else:
        body = "# no new resources suggested\n"
    out_path.write_text(_BANNER + body, encoding="utf-8")
    return out_path, len(flat)


def suggest_resources_cmd(
    workspace: str = typer.Option("", "--workspace", help="Workspace root (defaults to GRAPH_WIKI_WORKSPACE)"),
) -> None:
    """Propose graph.resources entries from existing graph facts."""
    _repo_root, workspace_root = _resolve_paths(workspace)
    try:
        out_path, n = compute_and_write(workspace_root)
    except InvalidMatcherRules as exc:
        typer.echo(f"error: {len(exc.errors)} invalid resource_matcher rule(s):", err=True)
        for e in exc.errors:
            typer.echo(f"  - {e}", err=True)
        raise typer.Exit(code=2)
    except GraphNotInitializedError as exc:
        typer.echo(f"error: graph not initialized: {exc}", err=True)
        raise typer.Exit(code=2)
    typer.echo(f"Wrote {n} suggested resource(s) to {out_path}")
