"""Phase 48 — `graph propose-domains` core module.

Consumes Phase 47's `compute_clusters` output (D-23: in-process import — NOT a
subprocess to `cg domain-clusters`), fans out one LLM call per cluster via
`SubagentPool` (D-01), aggregates results, applies mechanical cross-cutting
detection (D-07/D-08), grounds against `list_packages` (D-09), strips
cycle-introducing proposed parent edges (D-10..D-12), and writes a
human-review-only `domains.proposed.yaml` artifact (D-13..D-16).

PROPOSE-05 isolation is STRUCTURAL: `graph_io.domains._load_domains_yaml`
reads `domains.yaml` by literal filename. No allowlist edit needed — Plan
03's integration test pins this as a regression invariant.

Decision references (see .planning/phases/48-graph-propose-domains/48-CONTEXT.md):
  D-01 per-cluster fan-out via SubagentPool, partial-success
  D-02 per-package context = name + summary + file_map
  D-03 cluster prompt includes 'hubs used' annotation
  D-04 prompt skeleton + existing_domain_names as parent options
  D-05 Bedrock tool-use with strict JSON schema (_PROPOSE_DOMAIN_TOOL)
  D-06 ProposedDomain / ProposeResult dataclasses
  D-07 mechanical cross-cutting domain (no LLM call)
  D-08 name "cross-cutting" hardcoded
  D-09 grounding = filter against list_packages
  D-10 cycle detection scope = union(proposed, existing) parent edges
  D-11 existing edges immune in cycle strip
  D-12 iterative DFS, no networkx
  D-13 output path = <workspace>/domains.proposed.yaml
  D-14 top-level key `proposed_domains:` (NOT `domains:`) + metadata block
  D-15 yaml.safe_dump(sort_keys=True, default_flow_style=False); deterministic
  D-16 overwrite on each invocation
  D-19 new domain-proposer role
  D-20 cost records via SubagentPool.run_all trace pipeline
  D-21 --model override via make_llm("domain-proposer", model_override=...)
  D-23 in-process import of compute_clusters
  D-24 module contents
  D-25 no new third-party dependencies
"""

from __future__ import annotations

import asyncio
import datetime
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Awaitable, Callable, Optional

import typer
import yaml

from graph_io.cluster import (
    Cluster,
    ClusterResult,
    CrossCuttingHub,
    compute_clusters,
)
from graph_io.queries import list_packages
from graph_io.store import GraphNotInitializedError, read_only_connect
from langchain_core.messages import HumanMessage
from model_adapter.loader import load_role_config, make_llm
from subagent_runtime.pool import FanOutResult, SubagentPool, TaskResult
from workspace_io.config import resolve as resolve_config
from workspace_io.paths import graph_dir

# --------------------------------------------------------------------------- #
# Constants
# --------------------------------------------------------------------------- #

# D-05: Bedrock tool-use schema. MUST match CONTEXT D-05 verbatim — the five
# properties and the four required keys are part of the prompt contract.
_PROPOSE_DOMAIN_TOOL: dict = {
    "name": "propose_domain",
    "description": (
        "Propose a name, parent, and description for the candidate domain."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "description": "lowercase, kebab-case, 1-3 words",
            },
            "packages": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "subset of input packages that belong to this proposed "
                    "domain (may exclude some if they don't fit)"
                ),
            },
            "parent": {
                "type": ["string", "null"],
                "description": (
                    "name of parent domain from <existing_domain_names>, or null"
                ),
            },
            "description": {
                "type": "string",
                "description": "one-sentence description (~15-25 words)",
            },
            "confidence": {
                "type": "number",
                "description": "0.0-1.0 self-rated confidence",
            },
        },
        "required": ["name", "packages", "description", "confidence"],
    },
}

# D-07/D-08: name is hardcoded; not configurable.
_CROSS_CUTTING_NAME = "cross-cutting"
_CROSS_CUTTING_DESCRIPTION = (
    "Cross-cutting utility packages imported by multiple domains. Generated "
    "mechanically from cg domain-clusters hub detection."
)

# D-14: banner comment written as the first line of domains.proposed.yaml.
_BANNER = (
    "# Generated by graph-wiki-agent graph propose-domains. "
    "Review before promoting to domains.yaml."
)


# --------------------------------------------------------------------------- #
# Dataclasses (D-06)
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class ProposedDomain:
    """One LLM-proposed (or mechanically-built) domain candidate."""

    name: str
    packages: tuple[str, ...]  # sorted
    parent: Optional[str]
    description: str
    confidence: float
    llm_origin: str  # "fan_out" or "cross_cutting"


@dataclass(frozen=True)
class ProposeResult:
    """Aggregate result of a `graph propose-domains` run."""

    proposed_domains: tuple[ProposedDomain, ...]  # sorted by name
    stripped_unknown_packages: tuple[str, ...]  # PROPOSE-02 strips
    stripped_cycle_edges: tuple[tuple[str, str], ...]  # PROPOSE-03 strips (child, parent)
    llm_failures: tuple[str, ...]  # cluster names whose LLM call failed
    total_cost_usd: float  # PROPOSE-06 aggregated cost (best-effort)


# --------------------------------------------------------------------------- #
# Tool-call parsing (D-05)
# --------------------------------------------------------------------------- #


def _parse_tool_call(resp: Any) -> Optional[ProposedDomain]:
    """Extract the first ``propose_domain`` tool call from an LLM response.

    Returns None when the response has no tool calls or no matching call.
    The returned ``ProposedDomain`` carries ``llm_origin='fan_out'`` (D-06).
    Packages are sorted (deterministic byte-output downstream — D-15).
    """
    tool_calls = getattr(resp, "tool_calls", None) or []
    for call in tool_calls:
        if call.get("name") != "propose_domain":
            continue
        args = call.get("args") or {}
        packages = tuple(sorted(args.get("packages", []) or []))
        return ProposedDomain(
            name=args["name"],
            packages=packages,
            parent=args.get("parent"),
            description=args["description"],
            confidence=float(args["confidence"]),
            llm_origin="fan_out",
        )
    return None


# --------------------------------------------------------------------------- #
# Grounding (D-09)
# --------------------------------------------------------------------------- #


def _strip_unknown_packages(
    proposed: tuple[ProposedDomain, ...],
    valid_packages: set[str],
) -> tuple[tuple[ProposedDomain, ...], tuple[str, ...]]:
    """Filter each proposed domain's packages against ``valid_packages``.

    A domain whose packages are ALL stripped is itself dropped (claude-discretion
    lean from CONTEXT). Per-strip stderr warning is emitted via ``typer.echo(...,
    err=True)``. Returns ``(kept_domains, sorted_stripped_names)``.
    """
    kept: list[ProposedDomain] = []
    stripped: set[str] = set()
    for domain in proposed:
        filtered = tuple(sorted(p for p in domain.packages if p in valid_packages))
        for missing in domain.packages:
            if missing not in valid_packages:
                stripped.add(missing)
                typer.echo(
                    f"warning: stripping unknown package '{missing}' proposed "
                    f"for domain '{domain.name}' — not in list_packages output",
                    err=True,
                )
        if not filtered:
            # D-09 + claude-discretion: drop domain entirely if no packages
            # survive grounding.
            continue
        kept.append(
            ProposedDomain(
                name=domain.name,
                packages=filtered,
                parent=domain.parent,
                description=domain.description,
                confidence=domain.confidence,
                llm_origin=domain.llm_origin,
            )
        )
    return tuple(kept), tuple(sorted(stripped))


# --------------------------------------------------------------------------- #
# Cycle detection (D-10, D-11, D-12)
# --------------------------------------------------------------------------- #


def _strip_cycle_edges(
    proposed_edges: list[tuple[str, str]],
    existing_edges: list[tuple[str, str]],
) -> tuple[list[tuple[str, str]], list[tuple[str, str]]]:
    """Strip cycle-introducing edges from ``proposed_edges``.

    Operates on ``union(proposed, existing)`` (D-10). Existing edges are
    immune (D-11) — only proposed edges may be removed. Cycle detection is
    iterative-DFS grey/black coloring (D-12; no recursion, no networkx).

    Determinism (D-15): ``proposed_edges`` are sorted lexicographically before
    the first scan so the first proposed edge encountered on a cycle is
    invariant across runs. ``existing_edges`` are also sorted to make the
    DFS path deterministic.

    Returns ``(kept_proposed, stripped_proposed)``; both are lists of
    ``(child, parent)`` tuples.
    """
    proposed = sorted(proposed_edges)
    existing_sorted = sorted(existing_edges)
    stripped: list[tuple[str, str]] = []

    while True:
        # Mark each edge with origin so we can identify a strippable one.
        # 'proposed' edges are strippable; 'existing' edges are immune.
        edges: list[tuple[str, str, str]] = [
            (c, p, "existing") for c, p in existing_sorted
        ] + [(c, p, "proposed") for c, p in proposed]

        # Build adjacency: child -> list of (parent, origin, edge_index)
        # We keep the edges sorted-then-stable so adjacency iteration order is
        # deterministic. Index into `edges` lets us recover the edge tuple
        # later if needed.
        adj: dict[str, list[tuple[str, str]]] = {}
        nodes: set[str] = set()
        for c, p, origin in edges:
            adj.setdefault(c, []).append((p, origin))
            nodes.add(c)
            nodes.add(p)

        # Iterative DFS with grey/black coloring.
        WHITE, GREY, BLACK = 0, 1, 2
        color = {n: WHITE for n in nodes}
        # Stack entries: (node, iterator over outgoing edges)
        # First proposed edge encountered on a back-edge cycle is the strip target.
        first_proposed_on_cycle: Optional[tuple[str, str]] = None

        for start in sorted(nodes):
            if color[start] != WHITE:
                continue
            # Track path so we can locate the first proposed edge along it.
            path: list[tuple[str, str, str]] = []
            # (node, iterator)
            stack: list[tuple[str, Any]] = [(start, iter(sorted(adj.get(start, []))))]
            color[start] = GREY

            while stack:
                node, it = stack[-1]
                try:
                    nxt, origin = next(it)
                except StopIteration:
                    color[node] = BLACK
                    stack.pop()
                    if path:
                        path.pop()
                    continue

                if color.get(nxt, WHITE) == GREY:
                    # Back-edge — cycle. The path from `nxt` back to `node`
                    # plus the edge (node, nxt) is the cycle. Find the first
                    # proposed edge along that cycle path; existing edges are
                    # immune.
                    # path holds (parent_node, child_node, origin) for each
                    # edge we've descended into. The closing edge is
                    # (node, nxt, origin).
                    closing_edge = (node, nxt, origin)
                    # Cycle edges: walk back through `path` until we re-find
                    # `nxt` as a source, then take the closing edge.
                    cycle_edges: list[tuple[str, str, str]] = []
                    for src, dst, o in reversed(path):
                        cycle_edges.append((src, dst, o))
                        if src == nxt:
                            break
                    cycle_edges.reverse()
                    cycle_edges.append(closing_edge)
                    for src, dst, o in cycle_edges:
                        if o == "proposed":
                            first_proposed_on_cycle = (src, dst)
                            break
                    if first_proposed_on_cycle is None:
                        # Cycle in existing edges only — pre-existing problem
                        # (D-11); we cannot strip it. Bail out to avoid an
                        # infinite loop.
                        break
                    # Strip and restart.
                    break

                if color.get(nxt, WHITE) == WHITE:
                    color[nxt] = GREY
                    path.append((node, nxt, origin))
                    stack.append((nxt, iter(sorted(adj.get(nxt, [])))))
                    continue

                # BLACK: already finished — no cycle via this edge.
                # (no action — outer loop next() will advance)

            if first_proposed_on_cycle is not None:
                break  # restart outer while loop with the edge removed

        if first_proposed_on_cycle is None:
            # No (strippable) cycle remains.
            return proposed, stripped

        # Strip the identified proposed edge and restart.
        stripped.append(first_proposed_on_cycle)
        typer.echo(
            "warning: stripping cycle-introducing parent edge: "
            f"'{first_proposed_on_cycle[0]}' -> '{first_proposed_on_cycle[1]}'",
            err=True,
        )
        proposed = [e for e in proposed if e != first_proposed_on_cycle]


# --------------------------------------------------------------------------- #
# Cross-cutting builder (D-07, D-08)
# --------------------------------------------------------------------------- #


def _build_cross_cutting_domain(
    cross_cutting: tuple[CrossCuttingHub, ...],
) -> Optional[ProposedDomain]:
    """Build the mechanical `cross-cutting` proposed domain (D-07).

    Returns None when the input tuple is empty (claude-discretion lean).
    No LLM call: name is hardcoded (D-08), confidence=1.0, llm_origin='cross_cutting'.
    """
    if not cross_cutting:
        return None
    packages = tuple(sorted(h.name for h in cross_cutting))
    return ProposedDomain(
        name=_CROSS_CUTTING_NAME,
        packages=packages,
        parent=None,
        description=_CROSS_CUTTING_DESCRIPTION,
        confidence=1.0,
        llm_origin="cross_cutting",
    )


# --------------------------------------------------------------------------- #
# Existing-domains loader (RESEARCH F-6 + CONTEXT D-04/D-10)
# --------------------------------------------------------------------------- #


def _load_existing_domains(workspace_root: Path) -> dict[str, dict]:
    """Return the existing ``domains.yaml`` mapping (``{name: info_dict}``).

    Missing file → ``{}`` (no error). Accepts BOTH shapes:
      - FLAT (as `cg update` consumes; e.g.
        `core: {packages: [foo]}\\nweb: {packages: [bar]}`)
      - NESTED (`{"domains": {core: ..., web: ...}}`)

    Returns the per-domain mapping (`{name: info_dict}`). Returns ``{}`` if
    the file is unreadable, malformed, or empty.
    """
    path = workspace_root / "domains.yaml"
    if not path.exists():
        return {}
    try:
        with path.open("r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except yaml.YAMLError as exc:
        typer.echo(f"warning: domains.yaml: parse error: {exc}", err=True)
        return {}
    if not isinstance(data, dict):
        return {}
    # Prefer nested shape if the top-level has a single `domains:` key that
    # maps to a dict-of-dicts — that's the explicit form. Otherwise treat
    # the file as flat (matches `graph_io.domains.emit` which iterates
    # `data.items()` directly).
    inner = data.get("domains")
    if isinstance(inner, dict) and all(
        isinstance(v, dict) for v in inner.values()
    ):
        return inner
    # Flat: each top-level key is a domain name mapping to its info dict.
    return {k: v for k, v in data.items() if isinstance(v, dict)}


def _existing_parent_edges(existing: dict[str, dict]) -> list[tuple[str, str]]:
    """Build a sorted ``[(child, parent), ...]`` list from existing domains.

    Used as the immune-edge set in cycle detection (D-11).
    """
    edges: list[tuple[str, str]] = []
    for child, info in existing.items():
        if not isinstance(info, dict):
            continue
        parent = info.get("parent")
        if parent:
            edges.append((child, parent))
    return sorted(edges)


# --------------------------------------------------------------------------- #
# YAML writer (D-14, D-15, D-16)
# --------------------------------------------------------------------------- #


def _write_proposed_yaml(
    result: ProposeResult,
    output_path: Path,
    *,
    cluster_command: str,
    model: str,
) -> None:
    """Write the proposal artifact to ``output_path`` (D-13/D-16: overwrite).

    Format (D-14):
      Line 1: banner comment
      Body:   yaml.safe_dump({"proposed_domains": {...}, "metadata": {...}},
                              sort_keys=True, default_flow_style=False)

    ``proposed_domains`` is a dict keyed by domain name; each value has
    ``packages, description, parent, confidence, llm_origin``.
    """
    proposed_dict: dict[str, dict] = {}
    for d in sorted(result.proposed_domains, key=lambda x: x.name):
        proposed_dict[d.name] = {
            "packages": list(d.packages),
            "description": d.description,
            "parent": d.parent,
            "confidence": d.confidence,
            "llm_origin": d.llm_origin,
        }

    metadata = {
        "generated_at": datetime.datetime.now(tz=datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        ),
        "cluster_command": cluster_command,
        "model": model,
        "total_cost_usd": float(result.total_cost_usd),
        "stripped_unknown_packages": list(result.stripped_unknown_packages),
        "stripped_cycle_edges": [list(pair) for pair in result.stripped_cycle_edges],
        "llm_failures": list(result.llm_failures),
    }

    payload = {
        "proposed_domains": proposed_dict,
        "metadata": metadata,
    }

    body = yaml.safe_dump(payload, sort_keys=True, default_flow_style=False)
    with output_path.open("w", encoding="utf-8") as f:
        f.write(_BANNER + "\n")
        f.write(body)


# --------------------------------------------------------------------------- #
# Per-cluster prompt + fan-out task (D-01..D-04)
# --------------------------------------------------------------------------- #


def _build_cluster_prompt(
    cluster: Cluster,
    *,
    hubs_used: tuple[str, ...],
    context_loader: Callable[[str], dict],
    existing_domain_names: tuple[str, ...],
) -> str:
    """Compose the human prompt for one cluster (D-02/D-03/D-04).

    `context_loader(pkg_name)` returns ``{"summary": str, "file_map": str}``.
    """
    package_blocks: list[str] = []
    for pkg_name in cluster.members:
        ctx = context_loader(pkg_name) if context_loader else {}
        summary = ctx.get("summary") or "<no summary available>"
        file_map = ctx.get("file_map") or ""
        block = f"- {pkg_name}: {summary}"
        if file_map:
            block += f"\n  File map:\n{file_map}"
        package_blocks.append(block)

    hubs_section = ""
    if hubs_used:
        hub_lines = "\n".join(f"- {h}" for h in hubs_used)
        hubs_section = (
            "\n\n## Cross-cutting hubs this cluster uses\n" + hub_lines
        )

    parent_options = (
        ", ".join(existing_domain_names) if existing_domain_names else "none"
    )

    return (
        "You are proposing a name and description for a candidate domain in "
        "a Python monorepo.\n\n"
        "The domain candidate contains these packages:\n\n"
        + "\n\n".join(package_blocks)
        + hubs_section
        + f"\n\nOptionally, you may propose a parent domain (one of: "
        f"{parent_options}).\n\n"
        "Use the propose_domain tool to return your proposal."
    )


def _make_cluster_task(
    *,
    hubs_by_cluster_id: dict[int, tuple[str, ...]],
    context_loader: Callable[[str], dict],
    existing_domain_names: tuple[str, ...],
    bound_llm: Any,
) -> Callable[[Cluster], Awaitable[TaskResult]]:
    """Return the per-cluster async task closure for SubagentPool (D-01)."""

    async def _propose_for_cluster(cluster: Cluster) -> TaskResult:
        prompt = _build_cluster_prompt(
            cluster,
            hubs_used=hubs_by_cluster_id.get(cluster.id, ()),
            context_loader=context_loader,
            existing_domain_names=existing_domain_names,
        )
        resp = await bound_llm.ainvoke([HumanMessage(content=prompt)])
        return TaskResult(value=_parse_tool_call(resp), response=resp)

    return _propose_for_cluster


# --------------------------------------------------------------------------- #
# Typer command body (D-21, D-23, D-24)
# --------------------------------------------------------------------------- #


def _resolve_paths(workspace_arg: str) -> tuple[Path, Path]:
    """Resolve (repo_root, workspace) from --workspace arg or GRAPH_WIKI_WORKSPACE."""
    if workspace_arg:
        cfg = resolve_config(Path(workspace_arg).resolve(), require_manifest=False)
    else:
        cfg = resolve_config(None, require_manifest=False)
    return cfg.repo_root, cfg.workspace


def _aggregate_fan_out(
    fan_result: FanOutResult,
) -> tuple[list[ProposedDomain], list[str]]:
    """Split FanOutResult into proposed domains + cluster-name failure list."""
    proposed: list[ProposedDomain] = []
    failures: list[str] = []
    for item, value in fan_result.successes:
        if isinstance(value, ProposedDomain):
            proposed.append(value)
        else:
            # _parse_tool_call returned None — count as a soft failure.
            cname = getattr(item, "name", str(item))
            failures.append(cname)
    for err in fan_result.errors:
        cname = getattr(err.item, "name", str(err.item))
        failures.append(cname)
    return proposed, failures


def propose_domains_cmd(
    workspace: str = typer.Option(
        "", "--workspace", help="Workspace root (defaults to GRAPH_WIKI_WORKSPACE)"
    ),
    hub_threshold: float = typer.Option(
        0.5, "--hub-threshold", help="Fraction-of-packages threshold for cross-cutting hub detection"
    ),
    model: Optional[str] = typer.Option(
        None, "--model", help="Override domain-proposer model_id (D-21)"
    ),
) -> None:
    """Propose candidate domains from cg domain-clusters via an LLM fan-out.

    Writes ``<repo_root>/domains.proposed.yaml`` (next to ``domains.yaml``)
    for human review. NEVER auto-applies; the user reviews, edits, and
    (optionally) merges into the authoritative ``domains.yaml``.
    """
    repo_root, workspace_root = _resolve_paths(workspace)

    # D-23: in-process compute_clusters — NOT a subprocess to cg.
    db_path = graph_dir(workspace_root) / "code.db"
    try:
        conn = read_only_connect(db_path)
    except GraphNotInitializedError as exc:
        typer.echo(f"error: graph not initialized: {exc}", err=True)
        raise typer.Exit(code=2)

    cluster_result: ClusterResult = compute_clusters(
        conn, hub_threshold=hub_threshold
    )

    # Existing domains (for parent options + cycle-immune edges).
    # `domains.yaml` lives at the REPO root (same path `graph_io.domains.emit`
    # reads it from); the workspace is the `.graph-wiki/` directory.
    existing = _load_existing_domains(repo_root)
    existing_edges = _existing_parent_edges(existing)
    existing_domain_names = tuple(sorted(existing.keys()))

    # D-09 grounding set.
    valid_packages = {n.name for n in list_packages(conn)}

    # D-03: hubs-by-cluster-id (invert CrossCuttingHub.connects_clusters).
    hubs_by_cluster_id: dict[int, list[str]] = {}
    for hub in cluster_result.cross_cutting:
        for cid in hub.connects_clusters:
            hubs_by_cluster_id.setdefault(cid, []).append(hub.name)
    hubs_by_cluster_id_tuple = {
        cid: tuple(sorted(names)) for cid, names in hubs_by_cluster_id.items()
    }

    # D-19/D-21: LLM construction.
    llm = make_llm("domain-proposer", model_override=model)
    role_cfg = load_role_config("domain-proposer")
    effective_model_id = model if model is not None else role_cfg["model_id"]
    bound_llm = llm.bind_tools([_PROPOSE_DOMAIN_TOOL])

    # D-02: per-package context loader. v1.8 leaves this minimal — the
    # planner intentionally deferred richer summary/file_map wiring to v1.9
    # eval. A no-op loader keeps the prompt focused on package names.
    def _empty_context(_pkg_name: str) -> dict:
        return {}

    cluster_task = _make_cluster_task(
        hubs_by_cluster_id=hubs_by_cluster_id_tuple,
        context_loader=_empty_context,
        existing_domain_names=existing_domain_names,
        bound_llm=bound_llm,
    )

    # D-01/D-20: SubagentPool fan-out — partial-success + trace records.
    pool = SubagentPool(trace_dir=workspace_root / ".graph-wiki" / "traces")
    fan_result = asyncio.run(
        pool.run_all(
            items=list(cluster_result.clusters),
            task=cluster_task,
            role="domain-proposer",
            model_id=effective_model_id,
            max_concurrency=role_cfg["max_concurrency"],
        )
    )

    proposed_list, llm_failures = _aggregate_fan_out(fan_result)

    # D-07: mechanical cross-cutting domain.
    cross_cutting_domain = _build_cross_cutting_domain(cluster_result.cross_cutting)
    if cross_cutting_domain is not None:
        proposed_list.append(cross_cutting_domain)

    # D-09: ground against list_packages.
    proposed_tuple, stripped_unknown = _strip_unknown_packages(
        tuple(proposed_list), valid_packages
    )

    # D-10/D-11/D-12: cycle-strip proposed parent edges.
    proposed_edges = [
        (d.name, d.parent) for d in proposed_tuple if d.parent
    ]
    kept_edges, stripped_cycle = _strip_cycle_edges(proposed_edges, existing_edges)
    kept_edge_set = set(kept_edges)
    stripped_edge_set = set(stripped_cycle)
    # Null-out parent on any domain whose edge was stripped.
    if stripped_edge_set:
        rebuilt: list[ProposedDomain] = []
        for d in proposed_tuple:
            if d.parent and (d.name, d.parent) in stripped_edge_set:
                rebuilt.append(
                    ProposedDomain(
                        name=d.name,
                        packages=d.packages,
                        parent=None,
                        description=d.description,
                        confidence=d.confidence,
                        llm_origin=d.llm_origin,
                    )
                )
            else:
                rebuilt.append(d)
        proposed_tuple = tuple(rebuilt)

    # D-20: total_cost_usd — best-effort sum from the FanOutResult trace
    # records. v1.8 leaves this at 0.0 because the trace-cost-aggregation
    # helper landed in subagent_runtime's per-call writer (D-20: "written
    # automatically by SubagentPool.run_all"); a separate aggregator across
    # the JSONL trace can be added in v1.9 without changing this schema.
    total_cost = 0.0
    _ = kept_edge_set  # kept_edges is implicit in proposed_tuple's parent fields

    result = ProposeResult(
        proposed_domains=tuple(
            sorted(proposed_tuple, key=lambda d: d.name)
        ),
        stripped_unknown_packages=stripped_unknown,
        stripped_cycle_edges=tuple(stripped_cycle),
        llm_failures=tuple(llm_failures),
        total_cost_usd=total_cost,
    )

    # D-13/D-14/D-15/D-16: write the artifact (overwrite).
    # Output sits next to `domains.yaml` at the repo root so reviewers can
    # diff the two side-by-side. The workspace is reserved for derived
    # `.graph-wiki/` state.
    output_path = repo_root / "domains.proposed.yaml"
    _write_proposed_yaml(
        result,
        output_path,
        cluster_command=f"cg domain-clusters --hub-threshold {hub_threshold}",
        model=effective_model_id,
    )

    typer.echo(f"wrote {output_path}")
    if llm_failures:
        typer.echo(
            f"warning: {len(llm_failures)} cluster(s) failed: "
            f"{', '.join(llm_failures)}",
            err=True,
        )
