from __future__ import annotations

"""End-to-end integration test for Phase 39 scan→graph wiring.

Runs `run_scan(workspace_path=...)` against a fresh fixture monorepo
(with no pre-existing graph DB) and asserts that:

  1. cg update created `<workspace>/.graph/code.db`
  2. The scan log contains `cg update complete: exit_code=0`
  3. At least one vault page was written under `<wiki>/packages/<name>/overview.md`
  4. The graph DB carries `pkg:`-prefixed URIs for the packages

The scanner LLM is stubbed (no Bedrock credentials required).

Run with: `pytest -m integration`.
"""

import asyncio
import os
import shutil
import sqlite3
import subprocess
import sys
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from graph_wiki_agent.commands import scan as scan_module
from graph_wiki_agent.commands.scan import run_scan, ScanResult

pytestmark = pytest.mark.integration

# Canonical GRAPH_WIKI_RUN_INTEGRATION gate — matches conftest.py:19-22 verbatim
# so the docs/testing.md grep gate sees this file as canonical (D-10).
INTEGRATION_GATE = pytest.mark.skipif(
    not os.environ.get("GRAPH_WIKI_RUN_INTEGRATION"),
    reason="Set GRAPH_WIKI_RUN_INTEGRATION=1 to run real scan→graph integration scenarios",
)


def _setup_fixture_monorepo(tmp_path: Path) -> Path:
    """Build a minimal workspace + monorepo skeleton run_scan can process.

    Layout::

        tmp_path/workspace/
          wiki/
            CLAUDE.md      # heuristic discovery (no pinned containers)
            log.md         # required by append_log
          repo/
            .git/          # cg update enforces a git repo
            packages/
              pkg-a/pyproject.toml + src/pkg_a/__init__.py
              pkg-b/pyproject.toml + src/pkg_b/__init__.py
    """
    workspace = tmp_path / "workspace"
    wiki = workspace / "wiki"
    repo = workspace / "repo"

    wiki.mkdir(parents=True)
    (wiki / "CLAUDE.md").write_text(
        "# Wiki\n\nNo pinned containers — heuristic discovery.\n"
    )
    (wiki / "log.md").write_text("", encoding="utf-8")

    repo.mkdir()
    for name, mod_name in (("pkg-a", "pkg_a"), ("pkg-b", "pkg_b")):
        pkg_root = repo / "packages" / name
        src = pkg_root / "src" / mod_name
        src.mkdir(parents=True)
        (src / "__init__.py").write_text(f'"""{name} stub."""\n')
        (pkg_root / "pyproject.toml").write_text(
            f'[project]\nname = "{name}"\nversion = "0.1.0"\n'
        )

    # Minimal git repo — cg update walks git ls-files.
    if shutil.which("git") is None:
        pytest.skip("git binary not available — integration test requires git")
    subprocess.run(["git", "init", "-q", "-b", "main"], cwd=repo, check=True)
    subprocess.run(
        ["git", "config", "user.email", "test@example.com"], cwd=repo, check=True
    )
    subprocess.run(["git", "config", "user.name", "test"], cwd=repo, check=True)
    subprocess.run(["git", "add", "-A"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "init"], cwd=repo, check=True)

    return workspace


@INTEGRATION_GATE
def test_run_scan_creates_graph_db_and_uri_derived_slug(tmp_path, monkeypatch):
    workspace = _setup_fixture_monorepo(tmp_path)
    wiki = workspace / "wiki"
    repo = workspace / "repo"
    monkeypatch.setenv("GRAPH_WIKI_WORKSPACE", str(workspace))

    # Stub the scanner LLM — no Bedrock credentials needed in CI.
    class _StubLLM:
        async def ainvoke(self, msgs):
            resp = MagicMock()
            resp.content = "# Stub page body\n\nGenerated by integration test stub.\n"
            resp.usage_metadata = {
                "input_tokens": 0,
                "output_tokens": 0,
                "total_tokens": 0,
            }
            return resp

    monkeypatch.setattr(scan_module, "make_llm", lambda role, *, model_override=None: _StubLLM())
    monkeypatch.setattr(
        scan_module,
        "load_role_config",
        lambda role: {
            "model_id": "fake-model",
            "max_concurrency": 1,
            "region": "us-east-1",
            "max_tokens": 100,
        },
    )

    # Run the scanner end-to-end.
    result: ScanResult = asyncio.run(
        run_scan(workspace_path=workspace, repo_path=repo, no_file_map=True)
    )

    # 1. cg update created the graph DB at workspace/.graph/code.db.
    db = workspace / ".graph" / "code.db"
    assert db.exists(), f"graph DB not created at {db}"

    # 2. Scan log records the successful update.
    log = (wiki / "log.md").read_text(encoding="utf-8")
    assert "cg update complete: exit_code=0" in log, f"missing log line in: {log!r}"

    # 3. At least one package became a vault page.
    added_or_updated = result.added + result.updated
    assert added_or_updated, (
        f"no pages added/updated; errors: {result.errors}; "
        f"state_gate: {result.state_gate}"
    )

    # 4. The graph carries pkg: URIs for the packages.
    conn = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    try:
        rows = conn.execute(
            "SELECT name, uri FROM nodes WHERE kind='package'"
        ).fetchall()
    finally:
        conn.close()
    assert any(
        r[1] and r[1].startswith("pkg:") for r in rows
    ), f"no pkg: URIs in graph: {rows}"
